// client/src/components/modals/ConnectModal.vue
<script setup lang="ts">
import { connectToServer } from '@/util/api/api';
import { ref } from 'vue';

const props = defineProps({
  onCloseModal: {
    type: Function,
    required: true,
  }
});

const address = ref('');
const nick = ref('');

const handleCloseModal = () => {
  props.onCloseModal();
}

const handleAddServer = () => {
  connectToServer({ address: address.value, port: 6667, nick: nick.value })
}

</script>

<template>
  <div @click="handleCloseModal"
    class="absolute flex justify-center items-center min-h-screen w-full bg-black opacity-50">
  </div>
  <div class="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 flex flex-col
    items-center gap-2 bg-blue-200 text-center opacity-100 px-4 py-2 rounded-md">
    <h2 class="m-0">Address</h2>
    <input v-model="address" type="text" class="bg-white px-2 py-1 border-2 border-blue-600 rounded-md" />
    <h2 class="m-0">Nick</h2>
    <input v-model="nick" type="text" class="bg-white px-2 py-1 border-2 border-blue-600 rounded-md" />
    <button @click="handleAddServer" type="button"
      class="text-white bg-blue-600 hover:bg-blue-700 hover:ring-2 hover:ring-blue-300 hover:cursor-pointer transition-all duration:200 px-2 py-1 rounded-md">Add</button>
  </div>
</template>

// angular-client/src/app/modals/connect-modal/connect-modal.component.ts
import { Input } from '@angular/core';
import { Component } from '@angular/core';

@Component({
  selector: 'app-connect-modal',
  standalone: true,
  imports: [],
  templateUrl: './connect-modal.component.html',
  styleUrl: './connect-modal.component.css',
})
export class ConnectModalComponent {
  @Input({ required: true }) onCloseModal!: () => void;

  address: string = '';
  nick: string = '';

  handleCloseModal(): void {
    this.onCloseModal();
  }

  handleAddServer(): void {
    // TODO: add api logic
    // connectToServer({ address: address.value, port: 6667, nick: nick.value });
  }
}

<div
  (click)="handleCloseModal()"
  class="absolute flex justify-center items-center min-h-screen w-full bg-black opacity-50"
></div>
<div
  class="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 flex flex-col items-center gap-2 bg-blue-200 text-center opacity-100 px-4 py-2 rounded-md"
>
  <h2 class="m-0">Address</h2>
  <input
    v-model="address"
    type="text"
    class="bg-white px-2 py-1 border-2 border-blue-600 rounded-md"
  />
  <h2 class="m-0">Nick</h2>
  <input
    v-model="nick"
    type="text"
    class="bg-white px-2 py-1 border-2 border-blue-600 rounded-md"
  />
  <button
    (click)="handleAddServer()"
    type="button"
    class="text-white bg-blue-600 hover:bg-blue-700 hover:ring-2 hover:ring-blue-300 hover:cursor-pointer transition-all duration:200 px-2 py-1 rounded-md"
  >
    Add
  </button>
</div>
