// client/src/components/chat/MessageInput.vue
<template>
  <div class="flex flex-row gap-4">
    <select class="border-2 border-blue-600 rounded-md">
      <option>
        SAY
      </option>
      <option>
        NICK
      </option>
    </select>
    <input type="text" class="w-full px-2 border-2 border-blue-600 rounded-md" />
    <button type="button" class="text-white bg-blue-600 px-2 py-1 rounded-md">Send</button>
  </div>
</template>

// angular-client/src/app/chat/messageinput/messageinput.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-messageinput',
  standalone: true,
  imports: [],
  templateUrl: './messageinput.component.html',
  styleUrl: './messageinput.component.css'
})
export class MessageinputComponent {

}

<div class="flex flex-row gap-4">
  <select class="border-2 border-blue-600 rounded-md">
    <option>SAY</option>
    <option>NICK</option>
  </select>
  <input type="text" class="w-full px-2 border-2 border-blue-600 rounded-md" />
  <button type="button" class="text-white bg-blue-600 px-2 py-1 rounded-md">
    Send
  </button>
</div>
